name: Where's Religion Users deploy on push to main.
on: 
  push:
    branches:
      main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master
      # - name: Create .env from secrets
      #   uses: SpicyPizza/create-envfile@v1.3
      #   with:
      #     envkey_MONGODBNAME: ${{ secrets.MONGODBNAME }}
      #     envkey_CLIENTID: ${{ secrets.CLIENTID }}
      #     envkey_AUDIENCE: ${{ secrets.AUDIENCE }}
      #     envkey_ISSUER_BASE_URL: ${{ secrets.ISSUER_BASE_URL }}
      # Set up NodeJS
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Install required deps for action
      - name: Install Dependencies
        uses: actions/checkout@master
      - run: npm install
      - run: npm run runtest
    deploy:
      needs: [test]
      strategy: 
        matrix:
            machines: [vlcdhprdp01]
      runs-on: ${{ matrix.machines }}
      steps:
        - uses: actions/checkout@master
        - run: |
            if [[ ! -e /srv/node/logs/lrda_users.txt ]]; then
                mkdir -p /srv/node/logs
                touch /srv/node/logs/lrda_users.txt
            fi
            cd /srv/node/lrda-users/
            pm2 stop lrda_users
            git stash
            git pull
            npm install
            pm2 start -i max bin/lrda_users.js
